/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Jenkins.Aula20192.HugoSilva;

public class Library {
    public boolean someLibraryMethod() {
        return false;
    }
}
